version: '3.9'
services: 
  prom-pushgateway:
    image: prom/pushgateway
    ports: 
      - 9091:9091
  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus:/etc/prometheus:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - 3000:3000
  exporter:
    build: .
    ports:
      - 8000:8000
    environment:
      - PUSH_GATEWAY_URL=prom-pushgateway:9091/
      - JOB_NAME=loadtest