version: '3.9'
services: 
  prom-pushgateway:
    image: prom/pushgateway
    ports: 
      - 9091:9091
    networks:
      - web
    labels:
      - "traefik.frontend.rule=Host:pushgateway.rhtapqe.com"
      - "traefik.port=9091"
  prometheus:
    image: prom/prometheus
    depends_on:
      - prom-pushgateway
    volumes:
      - ./monitoring/prometheus:/etc/prometheus:ro
    networks:
      - web
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    labels:
      - "traefik.frontend.rule=Host:prometheus.rhtapqe.com"
      - "traefik.port=9090"
  ingester:
    build: /ingester
    depends_on:
      - prom-pushgateway
      - prometheus
    ports:
      - 8000:8000
    networks:
      - web
    environment:
      - PUSH_GATEWAY_URL=prom-pushgateway:9091/
      - JOB_NAME=loadtest
    labels:
       - "traefik.frontend.rule=Host:ingester.rhtapqe.com"
       - "traefik.port=8000"
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
      - ingester
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - web
    labels:
      - "traefik.frontend.rule=Host:grafana.rhtapqe.com"
      - "traefik.port=3000"
networks:
  web:
    external: true
volumes:
  grafana_data: