version: '3.9'
services: 
  prom-pushgateway:
    image: prom/pushgateway
    ports: 
      - 9091:9091
    networks:
      - web
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.prom-pushgateway.rule=Host(`perf-pushgateway.rhtapqe.com`)'
      - 'traefik.http.routers.prom-pushgateway.tls=true'
      - 'traefik.http.routers.prom-pushgateway.tls.certresolver=le'
      - 'traefik.http.routers.prom-pushgateway.service=prom-pushgateway@docker'
      - 'traefik.http.services.prom-pushgateway.loadbalancer.server.port=9091'
  prometheus:
    image: prom/prometheus
    depends_on:
      - prom-pushgateway
    volumes:
      - ./monitoring/prometheus:/etc/prometheus:ro
    networks:
      - web
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.prometheus.rule=Host(`perf-prometheus.rhtapqe.com`)'
      - 'traefik.http.routers.prometheus.tls=true'
      - 'traefik.http.routers.prometheus.tls.certresolver=le'
      - 'traefik.http.routers.prometheus.service=prometheus@docker'
      - 'traefik.http.services.prometheus.loadbalancer.server.port=9090'
  ingester:
    build: .
    depends_on:
      - prom-pushgateway
      - prometheus
    ports:
      - 8000:8000
    networks:
      - web
    environment:
      - PUSH_GATEWAY_URL=prom-pushgateway:9091/
      - JOB_NAME=loadtest
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.ingester.rule=Host(`perf-ingester.rhtapqe.com`)'
      - 'traefik.http.routers.ingester.tls=true'
      - 'traefik.http.routers.ingester.tls.certresolver=le'
      - 'traefik.http.routers.ingester.service=ingester@docker'
      - 'traefik.http.services.ingester.loadbalancer.server.port=8000'
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
      - ingester
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana.ini:/etc/grafana/grafana.ini
    ports:
      - 3000:3000
    networks:
      - web
    #environment:
    #  - GF_SERVER_ROOT_URL=https://grafana.rhtapqe.com
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.grafana.rule=Host(`grafana.rhtapqe.com`)'
      - 'traefik.http.routers.grafana.tls=true'
      - 'traefik.http.routers.grafana.tls.certresolver=le'
      - 'traefik.http.routers.grafana.service=grafana@docker'
      - 'traefik.http.services.grafana.loadbalancer.server.port=3000'
networks:
  web:
    external: true