schemaVersion: 2.2.0
metadata:
  name: prometheus-devfile
components:
  - name: prometheus-build
    image:
      imageName: perf-prometheus:latest
      dockerfile:
        uri: Dockerfile
        buildContext: .
        rootRequired: false
  - name: prometheus-deploy
    attributes:
      deployment/replicas: 1
      deployment/cpuLimit: '500m'
      deployment/cpuRequest: 200m
      deployment/memoryLimit: 256Mi
      deployment/memoryRequest: 128Mi
      deployment/container-port: 9090
    kubernetes:
      uri: deploy/base/deployment.yaml
commands:
  - id: prometheus-build
    apply:
      component: prometheus-build
  - id: prometheus-deploy
    apply:
      component: prometheus-deploy
  - id: deploy
    composite:
      commands:
        - prometheus-build
        - prometheus-deploy
      group:
        kind: deploy
        isDefault: true