apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingester
  namespace: performance-monitoring
spec:
  selector:
    matchLabels:
      app: ingester
  replicas: 1
  template:
    metadata:
      labels:
        app: ingester
    spec:
      containers:
      - name: ingester
        image: quay.io/redhat-appstudio-qe/performance-monitoring:main
        ports:
        - containerPort: 9091
        env:
        - name: PUSH_GATEWAY_URL
          value: "pushgateway:9091"
        - name: JOB_NAME
          value: "loadtests"
        resources:
          requests:
            cpu: "250m"
            memory: 256Mi
          limits:
            cpu: "250m"
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ingester
  namespace: performance-monitoring
spec:
  selector:
    app: ingester
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ingester
  namespace: performance-monitoring
spec:
  to:
    kind: Service
    name: ingester
  port:
    targetPort: http

